#!/usr/bin/env bash

function prompt_user {
  echo "How many files are in the current directory?"
  read guess
}

actual=$(ls -1 | wc -l)

prompt_user

while [[ $guess -ne $actual ]]
do
  if [[ $guess -lt $actual ]]; then
    echo "Too low!"
  else
    echo "Too high!"
  fi
  prompt_user
done

echo "Congratulations! You guessed right: $actual"
